Nef 258 circular countdown
tmconsulting/tmc24-components pull request #92
Opened 2018-07-27 18:47 UTC by versoul

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing [guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

2018-07-27 18:55 UTC, shoomakov requested changes
Небольшая правка

2018-07-27 18:55 UTC, shoomakov commented on packages/circular-countdown/src/main.vue
> +      var pct = ((100 - percent) / 100) * c;
let или const

2018-07-27 19:03 UTC, shoomakov approved these changes

2018-07-28 09:33 UTC, mikrowelt approved these changes

2018-07-28 09:33 UTC, merged