Nef 681
tmconsulting/tmc24-components pull request #99
Opened 2018-08-28 22:24 UTC by Mgorunuch

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing [guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

2018-08-31 07:32 UTC, mikrowelt commented
![image](https://user-images.githubusercontent.com/1247546/44898963-1dbc7100-ad09-11e8-8ab6-1487c4be2b17.png)

2018-08-31 21:08 UTC, Mgorunuch commented
![image](https://user-images.githubusercontent.com/7422373/44935890-2f3e6100-ad7b-11e8-8305-e6f80f5060e7.png)

2018-08-31 21:09 UTC, Mgorunuch commented
![image](https://user-images.githubusercontent.com/7422373/44935922-49783f00-ad7b-11e8-85b1-9d7ba89c43e0.png)

2018-08-31 21:10 UTC, Mgorunuch commented
Моя версия полностью в бранче

2018-09-03 08:11 UTC, mikrowelt requested changes

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +<template>
в этой файле какая то жопа с отступами, аттрибутами и еще > на новой строке это ппц

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +<template>
аттрибута все переносить на новую строку кроме первого

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +      if (!~[this.activeValue, this.inactiveValue].indexOf(this.value)) {
плиз не надо так делать побитовые операторы не читабельны

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +        this.$emit('input', !this.checked ? this.activeValue : this.inactiveValue);
можно вынести в переменную зачем тукт duplicate code

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +          // set input's checked property
зачем эти комменты

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +        let newColor = this.checked ? this.activeColor : this.inactiveColor;
раз уже везде используется... стоит вынести

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +        !this.switchDisabled && this.handleChange();
if

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +      /* istanbul ignore if */
зачем это?

2018-09-03 08:11 UTC, mikrowelt commented on packages/switch/src/component.vue
> +            'on-color': 'on-color is renamed to active-color.',
зачем это

2018-09-03 08:11 UTC, mikrowelt commented on packages/theme-chalk/src/switch.scss
> +      &.tm-switch__labtm--right {
почему тут переименовано?

2018-09-04 08:18 UTC, mikrowelt approved these changes

2018-09-04 08:18 UTC, merged